[BALDE-19] Input Manager
bald-org/bald-engine pull request #13
Opened 2018-12-17 12:59 UTC by BIGbadEL

2018-12-17 16:37 UTC, piotrmoszkowicz commented
There's something wrong with your master repository. Let's talk about it today 😉

2018-12-28 17:57 UTC, Blinkuu commented on src/input/input_manager.h
> +#define MAX_KEYS 1024
Do we really have 1024 keys? Maybe there is some possibility to make it somewhat generic?

2018-12-28 17:58 UTC, Blinkuu commented on src/input/input_manager.h
> +#define MAX_MOUSE_BUTTONS 32
Same, as stated above.

2018-12-30 10:29 UTC, 4jeR commented on examples/input_example.cpp
> +        double x,y;
Declaring variables in a loop, is it possible to declare them once out of the loop ?

2018-12-30 10:44 UTC, BIGbadEL commented on examples/input_example.cpp
> +        double x,y;
doesn't matter with trivial types

2018-12-30 11:16 UTC, Blinkuu approved these changes
good lil' c++ master

2019-01-03 07:33 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param keycode GLFW macro e.g. GLfW_KEY_SPACE
Param type

2019-01-03 07:33 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param keycode GLFW macro e.g. GLfW_KEY_SPACE
Param type

2019-01-03 07:33 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param buttoncode GLFW macro e.g. GLFW_MOUSE_BUTTON_1
Param type

2019-01-03 07:38 UTC, piotrmoszkowicz requested changes
Overall nice, I have some question to the overall idea, but let's talk about it today irl.

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param keycode GLFW macro e.g. GLfW_KEY_SPACE
Return type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param buttoncode GLFW macro e.g. GLFW_MOUSE_BUTTON_1
Return type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @return           true if button was typed otherwise false
Param type, return type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param keycode         GLFW key id
Param type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param keycode         GLFW key id
Param type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param buttoncode      GLFW mouse button id
Param type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param buttoncode      GLFW mouse button id
Param type

2019-01-03 07:38 UTC, piotrmoszkowicz commented on src/input/input_manager.h
> +         * @param fun [void(*)()] void function with no parameter
Don't we rename it to the callback as it is set?

2019-01-03 07:38 UTC, piotrmoszkowicz commented on tests/input_test.cpp
> +    EXPECT_TRUE(glfwSetKeyCallback(window, key_callback) == NULL);
Why not EXPECT_THAT(glfwSet..., NULL) ?
https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#matchers

2019-01-03 15:22 UTC, piotrmoszkowicz approved these changes

2019-01-03 15:48 UTC, merged