[BALDE-42] Code maintenance
bald-org/bald-engine pull request #30
Opened 2019-04-17 21:13 UTC by Blinkuu

Fixed input example. Cleaned bunch of code in CMakeLists and InputManager. Added minor missing functions to InputManager.

2019-04-20 15:17 UTC, BIGbadEL approved these changes

2019-04-20 21:13 UTC, piotrmoszkowicz requested changes
https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/events/event_manager.cpp#L37
- change to region for loop

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/Log.h#L63
- remove that line

https://github.com/bald-org/bald-engine/blob/BALDE-42_Code_maintenance/src/events/mouse_events.h
https://github.com/bald-org/bald-engine/blob/BALDE-42_Code_maintenance/src/events/window_events.h
https://github.com/bald-org/bald-engine/blob/BALDE-42_Code_maintenance/src/events/key_events.h
- change classes' fields all to const

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/events/callback/handler.cpp#L13
- change value to 0 instead of erase

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/events/callback/handler.h#L79
- remove std::find
- change condition to either 0 or vector end

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/input/input_manager.h#L7
- Why local imports once is with <> and later with ""?

https://github.com/bald-org/bald-engine/blob/BALDE-42_Code_maintenance/src/input/input_manager.h
- Gimme more const! :)

https://github.com/bald-org/bald-engine/blob/BALDE-42_Code_maintenance/src/utils/file_manager.cpp
- Make discussion about what should be returned on error.

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/utils/file_manager.h#L21
- enum class

https://github.com/bald-org/bald-engine/blob/a171eef1cfa572109a23e729b7297002e03bc90a/src/utils/split_string.h#L7
- Maybe we should change to pch?

2019-04-24 06:37 UTC, BIGbadEL approved these changes

2019-04-24 23:18 UTC, piotrmoszkowicz approved these changes

2019-04-25 19:37 UTC, merged