[BALDE-31] Improve event system so that you will be able to access certain event in subscribe lambda/function
bald-org/bald-engine pull request #39
Opened 2019-05-08 20:52 UTC by BIGbadEL

2019-05-09 20:15 UTC, Blinkuu requested changes

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/application.cpp
> +    Application::Application() : m_Running(true), m_EventManager(std::make_unique<EventManager>()) {
Event manager should be initialized in the same manner as window -> after Log::Init(). It shouldn't be on initializer list, imho.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/application.h
> +#include "event_manager.h"
If we can forward declare EventManager for faster compile times, let's do it.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/application.h
> +        std::unique_ptr<EventManager> m_EventManager; /** < pointer to Main Event Manager >*/
Comments start with capital letter.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_async_function_handler.h
> +        explicit EventAsyncFunctionHandler(F&& fun, Args&& ... args): EventHandler<E>(fun, args...) {}
add space before ":"

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler.h
> + */
What is this comment?

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler.h
> +                CORE_LOG_WARN(
Format this to one line

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler_interface.cpp
> +    std::vector<bool> EventHandlerInterface::m_TakenID;
add end line above

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler_interface.cpp
> +            m_ID(0) {
We have to follow the convention. I believe right now the convention is to do it like this:
Ctor()
: *tab* m_Var1(...)
  *tab* m_Var2(...) {
}

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler_interface.h
> +    /**
endline above

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler_interface.h
> +    class EventHandlerInterface {
endline above

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/callback/event_handler_interface.h
> +                                                     for ex. remove one of such from some type of queue */
format second line so that it starts on the same height as the line above.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        * @brief    Constructor of EventManager class and performs counting of existing objects
Change it: EventManager constructor. Its role is to increase the static reference counter variable

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        * @param [F&&]           callback -> Function with which you subscribe to an event. It *HAS TO* take as first parameter an const reference to Event
Change it: callback -> Function with which you subscribe to an event. It *MUST* take Event reference as the first parameter

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        [[nodiscard]] bool IsEventInQueue() noexcept;
Make it static.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        ~EventManager();
Move destructor so that it is below ctor.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        inline void Call() noexcept;
Remove inline or move it to .h, otherwise, it has no effect.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        static int m_ReferenceCounter;
Add documentation

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        if (iter == m_Callbacks.end()) return;
We use no space.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +            if (( **it ) == id) {
We use no space after if.

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        for (auto ev : m_EventQueue) {
no space after for

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +            if (ev->Type() == typeid(T)) return true;
no space after for

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        if (iter == m_Callbacks.end()) return;
no space after for

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/event_manager.h
> +        while (!iter->second->empty()) {
no space after for

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/key_events.h
> +                :
: m_KeyCode{keycode} { }

2019-05-09 20:15 UTC, Blinkuu commented on engine/src/events/key_events.h
> +
remove enter

2019-05-09 20:18 UTC, piotrmoszkowicz commented on engine/src/application.h
> +#include "event_manager.h"
Include must be in alphabetical order.

2019-05-09 20:40 UTC, BIGbadEL commented on engine/src/application.h
> +#include "event_manager.h"
we can't

2019-05-09 20:40 UTC, BIGbadEL commented on engine/src/events/callback/event_handler.h
> + */
¯\_(ツ)_/¯

2019-05-10 08:29 UTC, Blinkuu requested changes

2019-05-10 08:29 UTC, Blinkuu commented on engine/src/events/callback/event_function_handler.h
> +        * @param [F&&]          fun -> Function which will be wrapped *HAS TO* take as first parameter an const reference to Event
fun -> Function which will be wrapped. This method MUST take const reference to Event as first parameter.

2019-05-10 08:29 UTC, Blinkuu commented on engine/src/events/callback/event_async_function_handler.h
> +                EventHandler<E>(fun, args...) { }
make it one-liner -> move it up

2019-05-10 09:05 UTC, Blinkuu approved these changes

2019-05-10 09:10 UTC, merged