[BALDE-47] Implement our own assertions
bald-org/bald-engine pull request #52
Opened 2019-05-24 15:52 UTC by BIGbadEL

2019-05-31 10:03 UTC, Blinkuu requested changes

2019-05-31 10:03 UTC, Blinkuu commented on engine/src/utils/bald_assert.h
> +//
I think bald_assert stuff should go into debug folder.

2019-07-18 12:12 UTC, Blinkuu requested changes

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/app/layer_stack.cpp
> +        BALD_ASSERT(state, "LayerStack", "Failed to initialized LayerStack", state);
initialize*

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
Is casting really necessary here?

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
Is casting really necessary here?

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
Is casting really necessary here?

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/debug/bald_assert.h
> +        const std::string _file; /**< name of a file where assertion occurred. >*/
Fix naming to match our convention

2019-07-18 12:12 UTC, Blinkuu commented on engine/src/core/debug/bald_assert.h
> +
Fix formatting.

2019-07-18 13:37 UTC, BIGbadEL commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
yes.

2019-07-18 13:37 UTC, BIGbadEL commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
yes

2019-07-22 09:23 UTC, Blinkuu commented on engine/src/core/app/layer_stack.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Layer, L>::value), "Layer is not the base of L");
why?

2019-07-23 09:53 UTC, Blinkuu requested changes

2019-07-23 09:53 UTC, Blinkuu commented on engine/src/core/events/event_manager.h
> +        BALD_STATIC_ASSERT(static_cast<bool >(std::is_base_of<Event, T>::value), "Event is not the base of T");
Remove all static casting and this will be ready to merge.

2019-07-23 16:12 UTC, Blinkuu approved these changes

2019-07-23 18:03 UTC, merged