[BALDE-84] Implement texture abstraction
bald-org/bald-engine pull request #69
Opened 2019-07-30 11:06 UTC by Blinkuu

2019-08-07 16:02 UTC, BIGbadEL requested changes

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/graphics/rendering/textures/texture.h
> +        unsigned char* m_Data = nullptr;
u_char

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +extern "C" unsigned char* stbi_load(char const *filename, int *x, int *y, int *channels_in_file, int desired_channels);
I think that we should have functions in utils that wrap stbi_... and then use our api here.

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +            BALD_ASSERT(false, "OpenGLTexture", "OpenGL only guarantees to support 16 textures per shader!", index);
why do you use if and then bald_assert? bald_assert already has if inside so Bald_assert(index < 16, ... would be enough here.

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +                case Bald::Graphics::TextureWrapMode::Repeat:           glTexParameteri(GL_TEXTURE_2D, coord, GL_REPEAT); break;
if you put in enum TextureWrapMode:: Repeat = GL_REPEAT and this would be one line.

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +                case Bald::Graphics::TextureWrapMode::Repeat:           glTexParameteri(GL_TEXTURE_2D, coord, GL_REPEAT); break;
and stop writing all these namespaces you are inside them!!!!!!!

2019-08-07 16:02 UTC, BIGbadEL commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +                case Bald::Graphics::TextureFilterMethod::Nearest:              glTexParameteri(GL_TEXTURE_2D, mode, GL_NEAREST); break;
the same thing as in TextureWrapMode

2019-08-08 09:03 UTC, Blinkuu commented on engine/src/core/platform/opengl/textures/opengl_texture.cpp
> +                case Bald::Graphics::TextureWrapMode::Repeat:           glTexParameteri(GL_TEXTURE_2D, coord, GL_REPEAT); break;
The whole point of this enum is to make this platform-agnostic...

2019-08-08 11:34 UTC, BIGbadEL approved these changes

2019-08-08 12:27 UTC, merged