[BALDE-89] Build balde-engine on travis
bald-org/bald-engine pull request #76
Opened 2019-10-06 18:49 UTC by Blinkuu

2019-10-07 21:01 UTC, BIGbadEL requested changes

2019-10-07 21:01 UTC, BIGbadEL commented on engine/CMakeLists.txt
> +	set(RELEASE_COMPILE_FLAGS -std=c++17 -Ofast -Werror)
define APPLE macro

2019-10-07 21:01 UTC, BIGbadEL commented on engine/CMakeLists.txt
> +	endif()
can we make it in one if statement -> LINUX_BUILD || APPLE_BUILD ?

2019-10-07 21:01 UTC, BIGbadEL commented on engine/src/core/debug/bald_assert.h
> +#if defined(LINUX) || defined(__APPLE__)
we should define our macro and use it.

2019-10-07 21:01 UTC, BIGbadEL commented on engine/src/core/utils/time/time.h
> +        auto time = std::localtime(&now_c);
why elif if it looks the same on LINUX?

2019-11-17 16:02 UTC, Blinkuu commented on engine/CMakeLists.txt
> +	endif()
No, we use different compiler flags for each system.

2019-11-17 16:27 UTC, BIGbadEL approved these changes

2019-11-17 16:28 UTC, merged